default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= "expert_app_admin" %>
  password: <%= Rails.application.credentials.development.database[:password] %>
  port: <%= "5432" %>
  host: <%= "127.0.0.1" %>
development:
  <<: *default
  database: expert_app_db_development
  port: 5432
test:
  <<: *default
  database: expert_app_db_test
  port: 5432
production:
  <<: *default
  database: expert_app_db